// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiazJC1fpNVFa715r_O3iJRzE53Rgvy0Y',
    appId: '1:361857795435:web:6a0d9cdd1c1e410bd1f82e',
    messagingSenderId: '361857795435',
    projectId: 'petshopp-a472d',
    authDomain: 'petshopp-a472d.firebaseapp.com',
    storageBucket: 'petshopp-a472d.appspot.com',
    measurementId: 'G-S0685WB1VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlHtjP0ZN7AS0EGzLBc1pmxxtoLPdrKKk',
    appId: '1:361857795435:android:1c7dc523713e4357d1f82e',
    messagingSenderId: '361857795435',
    projectId: 'petshopp-a472d',
    storageBucket: 'petshopp-a472d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPCx7HlDozJ6kBRzztgT_L7i9kcs9VhUk',
    appId: '1:361857795435:ios:759f4e6bbaa75672d1f82e',
    messagingSenderId: '361857795435',
    projectId: 'petshopp-a472d',
    storageBucket: 'petshopp-a472d.appspot.com',
    iosBundleId: 'com.example.lastestBroo',
  );
}
